Remove-Item  ".\src\Pavlova\Contents\src\1. Domain\Pav.Lova.Core\bin",
    ".\src\Pavlova\Contents\src\1. Domain\Pav.Lova.Core\obj",
    ".\src\Pavlova\Contents\src\2. Services\Email\Pav.Lova.Service.Email\bin",
    ".\src\Pavlova\Contents\src\2. Services\Email\Pav.Lova.Service.Email\obj",
    ".\src\Pavlova\Contents\src\2. Services\Email\Pav.Lova.Service.Email.Tests\bin",
    ".\src\Pavlova\Contents\src\2. Services\Email\Pav.Lova.Service.Email.Tests\obj",
    ".\src\Pavlova\Contents\src\2. Services\Mocks\Pav.Lova.Service.Mocks\bin",
    ".\src\Pavlova\Contents\src\2. Services\Mocks\Pav.Lova.Service.Mocks\obj",
    ".\src\Pavlova\Contents\src\2. Services\Mocks\Pav.Lova.Service.Mocks.Tests\bin",
    ".\src\Pavlova\Contents\src\2. Services\Mocks\Pav.Lova.Service.Mocks.Tests\obj",
    ".\src\Pavlova\Contents\src\3. Infrastructure\Pav.Lova.Infrastructure\bin",
    ".\src\Pavlova\Contents\src\3. Infrastructure\Pav.Lova.Infrastructure\obj",
    ".\src\Pavlova\Contents\src\3. Infrastructure\Pav.Lova.Infrastructure.Tests\bin",
    ".\src\Pavlova\Contents\src\3. Infrastructure\Pav.Lova.Infrastructure.Tests\obj",
    ".\src\Pavlova\Contents\src\4. Presentation\Pav.Lova.Presentation.Api\bin",
    ".\src\Pavlova\Contents\src\4. Presentation\Pav.Lova.Presentation.Api\obj",
    ".\src\Pavlova\Contents\.vs\"  -Force -Recurse -ErrorAction Ignore

Remove-Item  ".\src\CheeseCake\Contents\src\1. Domain\Pav.Lova.Core\bin",
    ".\src\CheeseCake\Contents\src\1. Domain\Pav.Lova.Core\obj",
    ".\src\CheeseCake\Contents\src\2. Infrastructure\Email\Pav.Lova.Infrastructure.Email\bin",
    ".\src\CheeseCake\Contents\src\2. Infrastructure\Email\Pav.Lova.Infrastructure.Email\obj",
    ".\src\CheeseCake\Contents\src\2. Infrastructure\Email\Pav.Lova.Infrastructure.Email.Tests\bin",
    ".\src\CheeseCake\Contents\src\2. Infrastructure\Email\Pav.Lova.Infrastructure.Email.Tests\obj",
    ".\src\CheeseCake\Contents\src\2. Infrastructure\Mocks\Pav.Lova.Infrastructure.Mocks\bin",
    ".\src\CheeseCake\Contents\src\2. Infrastructure\Mocks\Pav.Lova.Infrastructure.Mocks\obj",
    ".\src\CheeseCake\Contents\src\2. Infrastructure\Mocks\Pav.Lova.Infrastructure.Mocks.Tests\bin",
    ".\src\CheeseCake\Contents\src\2. Infrastructure\Mocks\Pav.Lova.Infrastructure.Mocks.Tests\obj",
    ".\src\CheeseCake\Contents\src\3. Services\Pav.Lova.Services\bin",
    ".\src\CheeseCake\Contents\src\3. Services\Pav.Lova.Services\obj",
    ".\src\CheeseCake\Contents\src\3. Services\Pav.Lova.Services.Tests\bin",
    ".\src\CheeseCake\Contents\src\3. Services\Pav.Lova.Services.Tests\obj",
    ".\src\CheeseCake\Contents\src\4. Presentation\Pav.Lova.Presentation.Api\bin",
    ".\src\CheeseCake\Contents\src\4. Presentation\Pav.Lova.Presentation.Api\obj",
    ".\src\CheeseCake\Contents\.vs\"  -Force -Recurse -ErrorAction Ignore

    Write-Host "Solution Cleaned."